/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as ConsultarRouteImport } from './routes/consultar'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as JugarRouteImport } from './routes/jugar'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelTrabajadorRouteImport } from './routes/panel.trabajador'
import { Route as PanelAdminIndexRouteImport } from './routes/panel.admin.index'
import { Route as PanelAdminAuditoriaRouteImport } from './routes/panel.admin.auditoria'
import { Route as PanelAdminComprobantesRouteImport } from './routes/panel.admin.comprobantes'
import { Route as PanelAdminEquipoRouteImport } from './routes/panel.admin.equipo'
import { Route as PanelAdminResultadosRouteImport } from './routes/panel.admin.resultados'
import { Route as PanelAdminSorteosRouteImport } from './routes/panel.admin.sorteos'
import { Route as PanelAdminTicketsRouteImport } from './routes/panel.admin.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarRoute = ConsultarRouteImport.update({
  id: '/consultar',
  path: '/consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const JugarRoute = JugarRouteImport.update({
  id: '/jugar',
  path: '/jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTrabajadorRoute = PanelTrabajadorRouteImport.update({
  id: '/trabajador',
  path: '/trabajador',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminIndexRoute = PanelAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminAuditoriaRoute = PanelAdminAuditoriaRouteImport.update({
  id: '/admin/auditoria',
  path: '/admin/auditoria',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminComprobantesRoute = PanelAdminComprobantesRouteImport.update({
  id: '/admin/comprobantes',
  path: '/admin/comprobantes',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminEquipoRoute = PanelAdminEquipoRouteImport.update({
  id: '/admin/equipo',
  path: '/admin/equipo',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminResultadosRoute = PanelAdminResultadosRouteImport.update({
  id: '/admin/resultados',
  path: '/admin/resultados',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminSorteosRoute = PanelAdminSorteosRouteImport.update({
  id: '/admin/sorteos',
  path: '/admin/sorteos',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminTicketsRoute = PanelAdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/consultar': typeof ConsultarRoute
  '/cuenta': typeof CuentaRoute
  '/guia': typeof GuiaRoute
  '/jugar': typeof JugarRoute
  '/panel': typeof PanelRouteWithChildren
  '/resultados': typeof ResultadosRoute
  '/panel/trabajador': typeof PanelTrabajadorRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/admin/auditoria': typeof PanelAdminAuditoriaRoute
  '/panel/admin/comprobantes': typeof PanelAdminComprobantesRoute
  '/panel/admin/equipo': typeof PanelAdminEquipoRoute
  '/panel/admin/resultados': typeof PanelAdminResultadosRoute
  '/panel/admin/sorteos': typeof PanelAdminSorteosRoute
  '/panel/admin/tickets': typeof PanelAdminTicketsRoute
  '/panel/admin/': typeof PanelAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/consultar': typeof ConsultarRoute
  '/cuenta': typeof CuentaRoute
  '/guia': typeof GuiaRoute
  '/jugar': typeof JugarRoute
  '/resultados': typeof ResultadosRoute
  '/panel/trabajador': typeof PanelTrabajadorRoute
  '/panel': typeof PanelIndexRoute
  '/panel/admin/auditoria': typeof PanelAdminAuditoriaRoute
  '/panel/admin/comprobantes': typeof PanelAdminComprobantesRoute
  '/panel/admin/equipo': typeof PanelAdminEquipoRoute
  '/panel/admin/resultados': typeof PanelAdminResultadosRoute
  '/panel/admin/sorteos': typeof PanelAdminSorteosRoute
  '/panel/admin/tickets': typeof PanelAdminTicketsRoute
  '/panel/admin': typeof PanelAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/consultar': typeof ConsultarRoute
  '/cuenta': typeof CuentaRoute
  '/guia': typeof GuiaRoute
  '/jugar': typeof JugarRoute
  '/panel': typeof PanelRouteWithChildren
  '/resultados': typeof ResultadosRoute
  '/panel/trabajador': typeof PanelTrabajadorRoute
  '/panel/': typeof PanelIndexRoute
  '/panel/admin/auditoria': typeof PanelAdminAuditoriaRoute
  '/panel/admin/comprobantes': typeof PanelAdminComprobantesRoute
  '/panel/admin/equipo': typeof PanelAdminEquipoRoute
  '/panel/admin/resultados': typeof PanelAdminResultadosRoute
  '/panel/admin/sorteos': typeof PanelAdminSorteosRoute
  '/panel/admin/tickets': typeof PanelAdminTicketsRoute
  '/panel/admin/': typeof PanelAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/consultar'
    | '/cuenta'
    | '/guia'
    | '/jugar'
    | '/panel'
    | '/resultados'
    | '/panel/trabajador'
    | '/panel/'
    | '/panel/admin/auditoria'
    | '/panel/admin/comprobantes'
    | '/panel/admin/equipo'
    | '/panel/admin/resultados'
    | '/panel/admin/sorteos'
    | '/panel/admin/tickets'
    | '/panel/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/consultar'
    | '/cuenta'
    | '/guia'
    | '/jugar'
    | '/resultados'
    | '/panel/trabajador'
    | '/panel'
    | '/panel/admin/auditoria'
    | '/panel/admin/comprobantes'
    | '/panel/admin/equipo'
    | '/panel/admin/resultados'
    | '/panel/admin/sorteos'
    | '/panel/admin/tickets'
    | '/panel/admin'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/consultar'
    | '/cuenta'
    | '/guia'
    | '/jugar'
    | '/panel'
    | '/resultados'
    | '/panel/trabajador'
    | '/panel/'
    | '/panel/admin/auditoria'
    | '/panel/admin/comprobantes'
    | '/panel/admin/equipo'
    | '/panel/admin/resultados'
    | '/panel/admin/sorteos'
    | '/panel/admin/tickets'
    | '/panel/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  ConsultarRoute: typeof ConsultarRoute
  CuentaRoute: typeof CuentaRoute
  GuiaRoute: typeof GuiaRoute
  JugarRoute: typeof JugarRoute
  PanelRoute: typeof PanelRouteWithChildren
  ResultadosRoute: typeof ResultadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar': {
      id: '/consultar'
      path: '/consultar'
      fullPath: '/consultar'
      preLoaderRoute: typeof ConsultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugar': {
      id: '/jugar'
      path: '/jugar'
      fullPath: '/jugar'
      preLoaderRoute: typeof JugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/trabajador': {
      id: '/panel/trabajador'
      path: '/trabajador'
      fullPath: '/panel/trabajador'
      preLoaderRoute: typeof PanelTrabajadorRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/': {
      id: '/panel/admin/'
      path: '/admin'
      fullPath: '/panel/admin/'
      preLoaderRoute: typeof PanelAdminIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/auditoria': {
      id: '/panel/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/panel/admin/auditoria'
      preLoaderRoute: typeof PanelAdminAuditoriaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/comprobantes': {
      id: '/panel/admin/comprobantes'
      path: '/admin/comprobantes'
      fullPath: '/panel/admin/comprobantes'
      preLoaderRoute: typeof PanelAdminComprobantesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/equipo': {
      id: '/panel/admin/equipo'
      path: '/admin/equipo'
      fullPath: '/panel/admin/equipo'
      preLoaderRoute: typeof PanelAdminEquipoRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/resultados': {
      id: '/panel/admin/resultados'
      path: '/admin/resultados'
      fullPath: '/panel/admin/resultados'
      preLoaderRoute: typeof PanelAdminResultadosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/sorteos': {
      id: '/panel/admin/sorteos'
      path: '/admin/sorteos'
      fullPath: '/panel/admin/sorteos'
      preLoaderRoute: typeof PanelAdminSorteosRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin/tickets': {
      id: '/panel/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/panel/admin/tickets'
      preLoaderRoute: typeof PanelAdminTicketsRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelTrabajadorRoute: typeof PanelTrabajadorRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelAdminAuditoriaRoute: typeof PanelAdminAuditoriaRoute
  PanelAdminComprobantesRoute: typeof PanelAdminComprobantesRoute
  PanelAdminEquipoRoute: typeof PanelAdminEquipoRoute
  PanelAdminResultadosRoute: typeof PanelAdminResultadosRoute
  PanelAdminSorteosRoute: typeof PanelAdminSorteosRoute
  PanelAdminTicketsRoute: typeof PanelAdminTicketsRoute
  PanelAdminIndexRoute: typeof PanelAdminIndexRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelTrabajadorRoute: PanelTrabajadorRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelAdminAuditoriaRoute: PanelAdminAuditoriaRoute,
  PanelAdminComprobantesRoute: PanelAdminComprobantesRoute,
  PanelAdminEquipoRoute: PanelAdminEquipoRoute,
  PanelAdminResultadosRoute: PanelAdminResultadosRoute,
  PanelAdminSorteosRoute: PanelAdminSorteosRoute,
  PanelAdminTicketsRoute: PanelAdminTicketsRoute,
  PanelAdminIndexRoute: PanelAdminIndexRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  ConsultarRoute: ConsultarRoute,
  CuentaRoute: CuentaRoute,
  GuiaRoute: GuiaRoute,
  JugarRoute: JugarRoute,
  PanelRoute: PanelRouteWithChildren,
  ResultadosRoute: ResultadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
